//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationBasicAndAdditionalSettings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationBasicAndAdditionalSettings.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление прямого канала.
        /// </summary>
        internal static string add_downlink_channel {
            get {
                return ResourceManager.GetString("add_downlink_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные настройки.
        /// </summary>
        internal static string additional_settings {
            get {
                return ResourceManager.GetString("additional_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корректировать.
        /// </summary>
        internal static string adjustment {
            get {
                return ResourceManager.GetString("adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ослабление.
        /// </summary>
        internal static string attenuation {
            get {
                return ResourceManager.GetString("attenuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автовыбор.
        /// </summary>
        internal static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоподбор.
        /// </summary>
        internal static string autoselect {
            get {
                return ResourceManager.GetString("autoselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные настройки.
        /// </summary>
        internal static string basic_settings {
            get {
                return ResourceManager.GetString("basic_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал пеленгования.
        /// </summary>
        internal static string channel_direction_finding {
            get {
                return ResourceManager.GetString("channel_direction_finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер канала.
        /// </summary>
        internal static string channel_number {
            get {
                return ResourceManager.GetString("channel_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПАМ.
        /// </summary>
        internal static string df {
            get {
                return ResourceManager.GetString("df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия ПАМ.
        /// </summary>
        internal static string df_version {
            get {
                return ResourceManager.GetString("df_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямой канал.
        /// </summary>
        internal static string direct_channel {
            get {
                return ResourceManager.GetString("direct_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер прямого канала.
        /// </summary>
        internal static string direct_сhannel_number {
            get {
                return ResourceManager.GetString("direct_сhannel_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррекция расстояния, м.
        /// </summary>
        internal static string distance_correction {
            get {
                return ResourceManager.GetString("distance_correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый радиоканал используется под входящуюю связь.
        /// </summary>
        internal static string first_radio_ch_used_incoming_calls {
            get {
                return ResourceManager.GetString("first_radio_ch_used_incoming_calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы со сменой частот.
        /// </summary>
        internal static string frequency_change_model {
            get {
                return ResourceManager.GetString("frequency_change_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частотный канал перенаправления.
        /// </summary>
        internal static string frequency_channel_redirection {
            get {
                return ResourceManager.GetString("frequency_channel_redirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частотные каналы.
        /// </summary>
        internal static string frequency_channels {
            get {
                return ResourceManager.GetString("frequency_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота канала.
        /// </summary>
        internal static string frequensy_channel {
            get {
                return ResourceManager.GetString("frequensy_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификаторы.
        /// </summary>
        internal static string identifiers {
            get {
                return ResourceManager.GetString("identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящая связь.
        /// </summary>
        internal static string IncomingCalls {
            get {
                return ResourceManager.GetString("IncomingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим.
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. мощн., дБм, м.
        /// </summary>
        internal static string ms_power {
            get {
                return ResourceManager.GetString("ms_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        internal static string not_defined {
            get {
                return ResourceManager.GetString("not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не используется.
        /// </summary>
        internal static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С получением идентификатора - при наличии.
        /// </summary>
        internal static string OnReceeiptIdentifiers_availability {
            get {
                return ResourceManager.GetString("OnReceeiptIdentifiers_availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С получением идентификатора - всегда.
        /// </summary>
        internal static string OnReceiptIdentifiers_always {
            get {
                return ResourceManager.GetString("OnReceiptIdentifiers_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы на частоте, мм:сс.
        /// </summary>
        internal static string operating_time_frequency {
            get {
                return ResourceManager.GetString("operating_time_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходящая связь.
        /// </summary>
        internal static string OutgoingCalls {
            get {
                return ResourceManager.GetString("OutgoingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радиоканалы.
        /// </summary>
        internal static string radio_channels {
            get {
                return ResourceManager.GetString("radio_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенаправление на GSM.
        /// </summary>
        internal static string redirection_to_GSM {
            get {
                return ResourceManager.GetString("redirection_to_GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрации.
        /// </summary>
        internal static string Registrations {
            get {
                return ResourceManager.GetString("Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный канал.
        /// </summary>
        internal static string reverse_channel {
            get {
                return ResourceManager.GetString("reverse_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указать частотный канал вручную.
        /// </summary>
        internal static string set_specify_frequency_channel {
            get {
                return ResourceManager.GetString("set_specify_frequency_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Вт/{1} дБм.
        /// </summary>
        internal static string show_dBm {
            get {
                return ResourceManager.GetString("show_dBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандарт.
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало зоны поиска, м.
        /// </summary>
        internal static string start_search_area {
            get {
                return ResourceManager.GetString("start_search_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подавление.
        /// </summary>
        internal static string Suppression {
            get {
                return ResourceManager.GetString("Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передатчик.
        /// </summary>
        internal static string transmitter {
            get {
                return ResourceManager.GetString("transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключено.
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варианты использования.
        /// </summary>
        internal static string use_cases {
            get {
                return ResourceManager.GetString("use_cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать GPRS в работе.
        /// </summary>
        internal static string use_GPRS {
            get {
                return ResourceManager.GetString("use_GPRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия 1.0.
        /// </summary>
        internal static string Version1 {
            get {
                return ResourceManager.GetString("Version1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия 2.0.
        /// </summary>
        internal static string Version2 {
            get {
                return ResourceManager.GetString("Version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без получения идентификатора.
        /// </summary>
        internal static string WithoutObtainingIDs {
            get {
                return ResourceManager.GetString("WithoutObtainingIDs", resourceCulture);
            }
        }
    }
}
